name: iex
description: IEXCloud API interface.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.0
  path_provider: ^2.0.1

  # -dev version required due to 1.0.10 incompatibility with latest Flutter / Dart
  objectdb: ^1.0.12+1-dev

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

