name: iex
description: IEXCloud API interface.
version: 0.0.1
homepage: 'https://github.com/jonny7737/iex'

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.1
  path_provider: ^2.0.1

  objectdb: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

