name: iex
description: IEXCloud API interface.
version: 0.0.3
homepage: 'https://github.com/jonny7737/iex'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

analyzer:
  enable-experiment:
    - non-nullable

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.1
  intl: ^0.17.0

  objectdb: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

